name: Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          build-essential ccache git libncurses5:i386 libstdc++6:i386 \
          libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 \
          libidn11:i386 python3-dev zlib1g-dev zlib1g:i386 \
          openjdk-17-jdk unzip libffi-dev libssl-dev autoconf libtool pkg-config

    - name: Install Cython and Buildozer
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.36 buildozer

    - name: Build Android APK
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
    
